### ISSUE TITLE
Can not get 'grid' data and possibility of change input for SoC

### ISSUE THREAD

**Issue by robermf** [frnandu/diypowerflow#3]
Hello. 
First of all thank you for this code. I really love it!
But I have the next problem: 
It is impossible to get displayed the watts from the grid. The MQTT topic working, I have check a few times. Also tried with other data (from water heater, and others that works: solar, battery and house)
What am I doing wrong? I am out of ideas. 

And I have another question: 
It would be possible to change the way of get SoC (get from MQTT topic instead influx query)?

Thank you again. 
Best regards.

**Comment by frnandu** [comment]
Hi, 
thanks for poiting out the missing code for grid, I had the fix on my local rep but somehow forgot to commit it.
Should be working now.
As for the SoC from MQTT topic, yes I'm planning on doing that, just did not had the chance/time to get to it. If you're up to code it, feel free to post a pull request.
Cheers

**Comment by robermf** [comment]
Hello. 
Now works perfect! Thank you very much. 

My coding skills are very limited. But I will try to figure out how to do it :)

Regards.
